name: Deploy NestJS Auth

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t your-dockerhub-username/nestjs-auth .
          docker push your-dockerhub-username/nestjs-auth

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy to Server
        run: |
          ssh user@your-server-ip "docker pull ammarsharif/nestjs-auth && docker stop nestjs-auth || true && docker rm nestjs-auth || true && docker run -d -p 3000:3000 --name nestjs-auth ammarsharif/nestjs-auth"
